apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-deploy
  labels:
    app: MyApp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: sacpc/jen:4
